name: "AniSearch"
guid: "776d9158-b91f-49d9-82c5-dacce63d63b8"
imageUrl: "https://repo.jellyfin.org/releases/plugin/images/jellyfin-plugin-anisearch.png"
version: "5"
targetAbi: "10.9.0.0"
framework: "net8.0"
owner: "jellyfin"
overview: "AniSearch metadata provider"
description: >
  AniSearch metadata provider

category: "Metadata"
artifacts:
  - "Jellyfin.Plugin.AniSearch.dll"
changelog: |2-
