name: "AniSearch"
guid: "776d9158-b91f-49d9-82c5-dacce63d63b8"
imageUrl: "https://repo.jellyfin.org/releases/plugin/images/jellyfin-plugin-anisearch.png"
version: 6
targetAbi: "10.11.0.0"
framework: "net9.0"
owner: "jellyfin"
overview: "AniSearch metadata provider"
description: >
  AniSearch metadata provider

category: "Anime"
artifacts:
  - "Jellyfin.Plugin.AniSearch.dll"
changelog: |-
  - Jellyfin 10.11 support (#28) @crobibero
